/**
 * extractGrooveLoops.ts — One-time preprocessing script.
 *
 * Reads the Groove MIDI Dataset and extracts representative 2-bar drum loops
 * per style, writing them to src/data/jam/drumLoops.ts.
 *
 * Usage:
 *   npx tsx scripts/extractGrooveLoops.ts --dataset /path/to/groove/drummer1/session1
 *
 * Dataset: https://magenta.tensorflow.org/datasets/groove (CC BY 4.0)
 * The raw dataset is NOT committed; only the extracted TypeScript output is.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { Midi } from '@tonejs/midi';

// ---------------------------------------------------------------------------
// CLI args
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
const datasetFlag = args.indexOf('--dataset');
const DATASET_DIR = datasetFlag >= 0 ? args[datasetFlag + 1] : './groove';
const OUT_FILE = path.resolve(__dirname, '../src/data/jam/drumLoops.ts');

// ---------------------------------------------------------------------------
// Genre tag → our style mapping
// ---------------------------------------------------------------------------

type Style = 'rock' | 'funk' | 'blues' | 'reggae';

const GENRE_MAP: Record<string, Style> = {
  rock: 'rock',
  funk: 'funk',
  blues: 'blues',
  reggae: 'reggae',
  'afrobeat': 'funk',
};

// ---------------------------------------------------------------------------
// GM drum note constants (same as drumLoops.ts)
// ---------------------------------------------------------------------------

const IMPORTANT_NOTES = new Set([36, 38, 40, 42, 44, 46, 49, 51, 45, 48, 50]);

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface DrumEvent {
  time: number;
  note: number;
  velocity: number;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function walkMidi(dir: string): string[] {
  const results: string[] = [];
  if (!fs.existsSync(dir)) return results;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...walkMidi(full));
    else if (entry.name.endsWith('.mid') || entry.name.endsWith('.midi')) results.push(full);
  }
  return results;
}

function detectStyle(filePath: string): Style | null {
  const lower = filePath.toLowerCase();
  for (const [tag, style] of Object.entries(GENRE_MAP)) {
    if (lower.includes(tag)) return style;
  }
  return null;
}

function extractLoop(midi: Midi, barsToExtract = 2): DrumEvent[] | null {
  const drumTrack = midi.tracks.find(t =>
    t.channel === 9 || t.name.toLowerCase().includes('drum') || t.notes.some(n => n.midi >= 35 && n.midi <= 81)
  );
  if (!drumTrack || drumTrack.notes.length < 8) return null;

  const ppq = midi.header.ppq;
  const bpb = 4; // beats per bar (all 4/4)
  const loopEndTick = ppq * bpb * barsToExtract;

  const events: DrumEvent[] = drumTrack.notes
    .filter(n => n.ticks < loopEndTick && IMPORTANT_NOTES.has(n.midi))
    .map(n => ({
      time: parseFloat((n.ticks / ppq).toFixed(4)),
      note: n.midi,
      velocity: Math.round(n.velocity * 127),
    }));

  return events.length >= 6 ? events : null;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log(`Scanning ${DATASET_DIR}…`);
  const files = walkMidi(DATASET_DIR);
  console.log(`Found ${files.length} MIDI files`);

  const loops: Record<Style, DrumEvent[][]> = { rock: [], funk: [], blues: [], reggae: [] };
  const MAX_PER_STYLE = 2;

  for (const file of files) {
    const style = detectStyle(file);
    if (!style || loops[style].length >= MAX_PER_STYLE) continue;

    try {
      const buf = fs.readFileSync(file);
      const midi = new Midi(buf);
      const loop = extractLoop(midi);
      if (loop) {
        loops[style].push(loop);
        console.log(`  [${style}] extracted ${loop.length} events from ${path.basename(file)}`);
      }
    } catch {
      // skip corrupt files
    }
  }

  // Report missing styles
  for (const style of Object.keys(loops) as Style[]) {
    if (loops[style].length === 0) {
      console.warn(`  WARNING: no loops found for style "${style}" — fallback patterns will be used`);
    }
  }

  // ---------------------------------------------------------------------------
  // Emit TypeScript
  // ---------------------------------------------------------------------------

  const loopsJson = JSON.stringify(loops, null, 2);

  const output = `// AUTO-GENERATED by scripts/extractGrooveLoops.ts — do not edit manually.
// Source: Groove MIDI Dataset (CC BY 4.0) https://magenta.tensorflow.org/datasets/groove

import type { Style } from './progressions';

export interface DrumEvent {
  time: number;
  note: number;
  velocity: number;
}

export const GM = {
  KICK:            36,
  SNARE:           38,
  SNARE_GHOST:     40,
  HI_HAT_CLOSED:  42,
  HI_HAT_PEDAL:   44,
  HI_HAT_OPEN:    46,
  CRASH:           49,
  RIDE:            51,
  LOW_TOM:         45,
  MID_TOM:         48,
  HI_TOM:          50,
} as const;

export const LOOP_BARS: Record<Style, number> = {
  rock:   2,
  funk:   2,
  blues:  2,
  reggae: 2,
};

export const DRUM_LOOPS: Record<Style, DrumEvent[][]> = ${loopsJson};
`;

  fs.writeFileSync(OUT_FILE, output, 'utf8');
  console.log(`\nWrote ${OUT_FILE}`);
}

main().catch(console.error);
